//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIPS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string SlackID { get; set; }
        public int TotalPoints { get; set; }
        public int SemesterPoints { get; set; }
        public int WeekPoints { get; set; }
        public int AccessLevel { get; set; }
    }
}
